version: "3"

services:
    backend:
        build:
            context: ./www
        ports:
            - "3000:3000"
        depends_on:
            - redis
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_DB: 0
        command: >
            sh -c "
            node seed.js &&
            npm start
            "

    frontend:
        build:
            context: ./app
        ports:
            - "3001:3000"
        depends_on:
            - backend

    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"

    test:
        build:
            context: ./www
        depends_on:
            - backend
            - redis
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_DB: 1
        command: npm test
